# -*- coding: utf-8 -*-
"""Agent5_Recom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V75fZybVd5Rw5ugRYQsi7pRsQvAGKvN
"""

!pip install -q pandas numpy sentence-transformers faiss-cpu pypdf tqdm

!pip install -q transformers accelerate bitsandbytes

import os
import re
import json
import pandas as pd
import numpy as np

from pathlib import Path
from tqdm.auto import tqdm

import faiss

from pypdf import PdfReader
from sentence_transformers import SentenceTransformer

from google.colab import files

uploaded = files.upload()

csv_files = [
    filename
    for filename in uploaded.keys()
    if filename.lower().endswith(".csv")
]

if not csv_files:
    raise ValueError("No CSV file uploaded.")

CSV_PATH = csv_files[0]

df = pd.read_csv(CSV_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

required_columns = [
    "Region_ID",
    "State",
    "District",
    "Latitude",
    "Longitude",
    "Forecast_Year",
    "Predicted_HMPI",
    "Risk_Level",
    "Risk_Explanation",
    "Major_Pollutants",
    "Pollution_Source",
    "Confidence",
    "Confidence_Level"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    print("Missing columns:", missing_columns)
else:
    print("✓ All required Agent 5 columns are present.")

print("\nMissing values:")
print(df[required_columns].isnull().sum())

print("\nDataset shape:", df.shape)

print("States:")
print(df["State"].value_counts())

print("\nDistricts:")
print(df["District"].value_counts())

print("\nRisk Levels:")
print(df["Risk_Level"].value_counts())

print("\nPollution Sources:")
print(df["Pollution_Source"].value_counts())

print("\nConfidence Levels:")
print(df["Confidence_Level"].value_counts())

print("\nMajor Pollutants:")
print(df["Major_Pollutants"].value_counts().head(20))

KNOWLEDGE_BASE_DIR = "/content/agent5_knowledge_base"

os.makedirs(
    KNOWLEDGE_BASE_DIR,
    exist_ok=True
)

print(
    "Knowledge base directory created:",
    KNOWLEDGE_BASE_DIR
)

from google.colab import files

print("Upload your RAG knowledge-base PDF documents.")

uploaded_docs = files.upload()

for filename, content in uploaded_docs.items():

    file_path = os.path.join(
        KNOWLEDGE_BASE_DIR,
        filename
    )

    with open(file_path, "wb") as f:
        f.write(content)

print("\nUploaded documents:")

for file in os.listdir(KNOWLEDGE_BASE_DIR):
    print("✓", file)

SOURCE_MAPPING = {
    "policy-1.pdf": "WHO",
    "policy-2.pdf": "BIS",
    "policy-3.pdf": "CGWB"
}

def identify_source_type(filename):
    return SOURCE_MAPPING.get(
        filename.lower(),
        "Research Paper"
    )

print("Document Source Mapping:\n")

for file in os.listdir(KNOWLEDGE_BASE_DIR):
    if file.lower().endswith(".pdf"):
        print(
            f"{file} --> {identify_source_type(file)}"
        )

from pypdf import PdfReader

def extract_pdf_text(pdf_path):

    reader = PdfReader(pdf_path)

    pages = []

    for page_number, page in enumerate(reader.pages):

        try:

            text = page.extract_text()

            if text and text.strip():

                pages.append({
                    "page": page_number + 1,
                    "text": text.strip()
                })

        except Exception as e:

            print(
                f"Error reading page {page_number + 1}: {e}"
            )

    return pages

from tqdm.auto import tqdm

documents = []

pdf_files = [
    file
    for file in os.listdir(KNOWLEDGE_BASE_DIR)
    if file.lower().endswith(".pdf")
]

print(
    "PDF files found:",
    len(pdf_files)
)

for filename in tqdm(pdf_files):

    pdf_path = os.path.join(
        KNOWLEDGE_BASE_DIR,
        filename
    )

    source_type = identify_source_type(
        filename
    )

    pages = extract_pdf_text(
        pdf_path
    )

    for page in pages:

        documents.append({

            "source": filename,

            "source_type": source_type,

            "page": page["page"],

            "text": page["text"]

        })


print(
    "\nTotal pages successfully extracted:",
    len(documents)
)

from collections import Counter

source_counts = Counter(
    doc["source_type"]
    for doc in documents
)

print(
    "Extracted pages by source:\n"
)

for source, count in source_counts.items():

    print(
        f"{source}: {count} pages"
    )

import re

def clean_text(text):

    # Remove null characters
    text = text.replace(
        "\x00",
        ""
    )

    # Replace excessive whitespace
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


for doc in documents:

    doc["text"] = clean_text(
        doc["text"]
    )


# Remove pages with almost no useful text

documents = [
    doc
    for doc in documents
    if len(doc["text"]) > 50
]


print(
    "Valid pages after cleaning:",
    len(documents)
)

for organization in [
    "WHO",
    "BIS",
    "CGWB"
]:

    print(
        "\n" + "=" * 80
    )

    print(
        organization
    )

    print(
        "=" * 80
    )

    sample_docs = [
        doc
        for doc in documents
        if doc["source_type"] == organization
    ]

    if sample_docs:

        sample = sample_docs[0]

        print(
            "File:",
            sample["source"]
        )

        print(
            "Page:",
            sample["page"]
        )

        print(
            "\nText:"
        )

        print(
            sample["text"][:1000]
        )

    else:

        print(
            "No extracted text found."
        )

def chunk_text(
    text,
    chunk_size=1200,
    overlap=200
):

    chunks = []

    start = 0

    while start < len(text):

        end = start + chunk_size

        chunk = text[
            start:end
        ]

        if len(
            chunk.strip()
        ) > 150:

            chunks.append(
                chunk.strip()
            )

        start += (
            chunk_size - overlap
        )

    return chunks

knowledge_chunks = []

chunk_id = 0

for doc in documents:

    chunks = chunk_text(
        doc["text"]
    )

    for chunk in chunks:

        knowledge_chunks.append({

            "chunk_id": chunk_id,

            "source": doc["source"],

            "source_type": doc["source_type"],

            "page": doc["page"],

            "text": chunk

        })

        chunk_id += 1


print(
    "Total RAG chunks:",
    len(knowledge_chunks)
)

chunk_source_counts = Counter(
    chunk["source_type"]
    for chunk in knowledge_chunks
)

print(
    "RAG chunks by source:\n"
)

for source, count in chunk_source_counts.items():

    print(
        f"{source}: {count} chunks"
    )

import numpy as np
import faiss

from sentence_transformers import SentenceTransformer


embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)


print(
    "✓ Embedding model loaded successfully"
)

chunk_texts = [
    chunk["text"]
    for chunk in knowledge_chunks
]


print(
    "Generating embeddings for",
    len(chunk_texts),
    "chunks..."
)


chunk_embeddings = embedding_model.encode(

    chunk_texts,

    batch_size=32,

    show_progress_bar=True,

    convert_to_numpy=True,

    normalize_embeddings=True
)


chunk_embeddings = np.asarray(
    chunk_embeddings,
    dtype="float32"
)


print(
    "\nEmbedding shape:",
    chunk_embeddings.shape
)

embedding_dimension = (
    chunk_embeddings.shape[1]
)


faiss_index = faiss.IndexFlatIP(
    embedding_dimension
)


faiss_index.add(
    chunk_embeddings
)


print(
    "✓ FAISS Vector Database Created"
)

print(
    "Total vectors:",
    faiss_index.ntotal
)

print(
    "Embedding dimension:",
    embedding_dimension
)

import pickle


FAISS_INDEX_PATH = (
    "/content/agent5_faiss.index"
)

METADATA_PATH = (
    "/content/agent5_metadata.pkl"
)


faiss.write_index(
    faiss_index,
    FAISS_INDEX_PATH
)


with open(
    METADATA_PATH,
    "wb"
) as f:

    pickle.dump(
        knowledge_chunks,
        f
    )


print(
    "✓ FAISS index saved:",
    FAISS_INDEX_PATH
)

print(
    "✓ Metadata saved:",
    METADATA_PATH
)

def retrieve_policy_context(
    query,
    top_k=10
):

    query_embedding = embedding_model.encode(

        [query],

        convert_to_numpy=True,

        normalize_embeddings=True
    )


    query_embedding = np.asarray(
        query_embedding,
        dtype="float32"
    )


    scores, indices = faiss_index.search(

        query_embedding,

        top_k
    )


    results = []


    for score, idx in zip(
        scores[0],
        indices[0]
    ):

        if idx == -1:
            continue


        result = (
            knowledge_chunks[idx].copy()
        )


        result[
            "similarity_score"
        ] = float(score)


        results.append(
            result
        )


    return results

def create_policy_query(row):

    query = f"""
    Find authoritative policy guidance,
    drinking water standards,
    groundwater contamination mitigation,
    treatment strategies and monitoring
    recommendations for the following case.

    Location:
    {row['District']}, {row['State']}

    Forecast Year:
    {row['Forecast_Year']}

    Predicted HMPI:
    {row['Predicted_HMPI']}

    Groundwater Risk Level:
    {row['Risk_Level']}

    Risk Explanation:
    {row['Risk_Explanation']}

    Major Heavy Metal Pollutants:
    {row['Major_Pollutants']}

    Pollution Source:
    {row['Pollution_Source']}

    Prediction Confidence:
    {row['Confidence']}

    Retrieve evidence relevant to:

    - Drinking water safety standards
    - Heavy metal contamination
    - Pollutant-specific mitigation
    - Groundwater monitoring
    - Treatment technologies
    - Geogenic or anthropogenic contamination
    - Government intervention
    - Groundwater management policy

    Prioritize BIS guidance for Indian
    drinking-water requirements,
    WHO for health and treatment guidance,
    and CGWB for Indian groundwater
    conditions and management.
    """

    return clean_text(
        query
    )

sample_row = df.iloc[0]


sample_query = create_policy_query(
    sample_row
)


print(
    "RAG QUERY:\n"
)

print(
    sample_query
)


retrieved_results = retrieve_policy_context(

    sample_query,

    top_k=10
)

for i, result in enumerate(
    retrieved_results,
    start=1
):

    print(
        "\n" + "=" * 100
    )

    print(
        f"RESULT {i}"
    )

    print(
        "Organization:",
        result["source_type"]
    )

    print(
        "Document:",
        result["source"]
    )

    print(
        "Page:",
        result["page"]
    )

    print(
        "Similarity:",
        round(
            result["similarity_score"],
            4
        )
    )

    print(
        "\nEvidence:"
    )

    print(
        result["text"][:1200]
    )

def retrieve_balanced_policy_context(
    query,
    per_source_k=4
):

    # Retrieve a larger candidate pool
    candidate_k = min(
        100,
        faiss_index.ntotal
    )

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    query_embedding = np.asarray(
        query_embedding,
        dtype="float32"
    )

    scores, indices = faiss_index.search(
        query_embedding,
        candidate_k
    )

    # Store candidates by source
    source_results = {
        "WHO": [],
        "BIS": [],
        "CGWB": []
    }

    for score, idx in zip(
        scores[0],
        indices[0]
    ):

        if idx == -1:
            continue

        result = knowledge_chunks[idx].copy()

        result["similarity_score"] = float(score)

        source = result["source_type"]

        if source in source_results:

            if len(source_results[source]) < per_source_k:

                source_results[source].append(
                    result
                )

    # Combine results
    final_results = []

    for source in [
        "BIS",
        "WHO",
        "CGWB"
    ]:

        final_results.extend(
            source_results[source]
        )

    return final_results

balanced_results = retrieve_balanced_policy_context(
    sample_query,
    per_source_k=4
)

print(
    "Total retrieved:",
    len(balanced_results)
)

print("\nRetrieved by source:\n")

for source in [
    "BIS",
    "WHO",
    "CGWB"
]:

    count = sum(
        1
        for result in balanced_results
        if result["source_type"] == source
    )

    print(
        f"{source}: {count}"
    )

for i, result in enumerate(
    balanced_results,
    start=1
):

    print(
        "\n" + "=" * 100
    )

    print(
        f"RESULT {i}"
    )

    print(
        "Organization:",
        result["source_type"]
    )

    print(
        "Document:",
        result["source"]
    )

    print(
        "Page:",
        result["page"]
    )

    print(
        "Similarity:",
        round(
            result["similarity_score"],
            4
        )
    )

    print(
        "\nEvidence:"
    )

    print(
        result["text"][:800]
    )

POLLUTANT_MAPPING = {

    "Arsenic_As": "arsenic",

    "Mercury_Hg": "mercury",

    "Nickel_Ni": "nickel",

    "Lead_Pb": "lead",

    "Cadmium_Cd": "cadmium",

    "Chromium_Cr": "chromium",

    "Iron_Fe": "iron",

    "Copper_Cu": "copper",

    "Zinc_Zn": "zinc",

    "Manganese_Mn": "manganese",

    "Selenium_Se": "selenium"
}


def extract_pollutants(
    pollutant_string
):

    pollutants = []

    parts = str(
        pollutant_string
    ).split("|")

    for part in parts:

        part = part.strip()

        pollutant = POLLUTANT_MAPPING.get(
            part,
            part
        )

        pollutants.append(
            pollutant
        )

    return pollutants

sample_pollutants = extract_pollutants(
    sample_row["Major_Pollutants"]
)

print(
    "Original:"
)

print(
    sample_row["Major_Pollutants"]
)

print(
    "\nNormalized:"
)

print(
    sample_pollutants
)

def retrieve_pollutant_evidence(
    pollutant,
    row,
    top_k=5
):

    query = f"""
    Authoritative drinking water and groundwater
    guidance for {pollutant} contamination.

    Location:
    {row['District']}, {row['State']}

    Pollution source:
    {row['Pollution_Source']}

    Risk level:
    {row['Risk_Level']}

    Find evidence about:

    {pollutant} drinking water limits,
    health risks,
    groundwater contamination,
    treatment and removal methods,
    mitigation strategies,
    monitoring requirements,
    and government interventions.

    Prioritize BIS IS 10500,
    WHO drinking-water guidelines,
    and CGWB groundwater guidance.
    """

    query = clean_text(
        query
    )

    results = retrieve_policy_context(
        query,
        top_k=top_k
    )

    return results

pollutant_results = {}

for pollutant in sample_pollutants:

    print(
        "\n" + "=" * 100
    )

    print(
        "POLLUTANT:",
        pollutant.upper()
    )

    print(
        "=" * 100
    )

    results = retrieve_pollutant_evidence(
        pollutant,
        sample_row,
        top_k=5
    )

    pollutant_results[
        pollutant
    ] = results

    for result in results[:3]:

        print(
            "\nOrganization:",
            result["source_type"]
        )

        print(
            "Page:",
            result["page"]
        )

        print(
            "Similarity:",
            round(
                result["similarity_score"],
                4
            )
        )

        print(
            result["text"][:500]
        )

def deduplicate_results(
    results
):

    seen = set()

    unique_results = []

    for result in results:

        key = (
            result["source"],
            result["page"],
            result["text"]
        )

        if key not in seen:

            seen.add(
                key
            )

            unique_results.append(
                result
            )

    return unique_results

def retrieve_complete_evidence(
    row
):

    # --------------------------------
    # 1. General policy query
    # --------------------------------

    general_query = create_policy_query(
        row
    )

    balanced_results = (
        retrieve_balanced_policy_context(
            general_query,
            per_source_k=3
        )
    )


    # --------------------------------
    # 2. Pollutant-specific retrieval
    # --------------------------------

    pollutants = extract_pollutants(
        row["Major_Pollutants"]
    )

    pollutant_results = []

    for pollutant in pollutants:

        results = (
            retrieve_pollutant_evidence(
                pollutant,
                row,
                top_k=4
            )
        )

        pollutant_results.extend(
            results
        )


    # --------------------------------
    # 3. Combine results
    # --------------------------------

    all_results = (
        balanced_results
        +
        pollutant_results
    )


    # --------------------------------
    # 4. Remove duplicate evidence
    # --------------------------------

    final_results = (
        deduplicate_results(
            all_results
        )
    )


    return final_results

complete_evidence = retrieve_complete_evidence(
    sample_row
)

print(
    "Total unique evidence chunks:",
    len(complete_evidence)
)


print(
    "\nEvidence by organization:"
)


for source in [
    "BIS",
    "WHO",
    "CGWB"
]:

    count = sum(
        1
        for result in complete_evidence
        if result["source_type"] == source
    )

    print(
        f"{source}: {count}"
    )

def build_rag_context(
    evidence_results
):

    context_parts = []

    for i, result in enumerate(
        evidence_results,
        start=1
    ):

        context = f"""
        [REFERENCE {i}]

        Organization:
        {result['source_type']}

        Document:
        {result['source']}

        Page:
        {result['page']}

        Evidence:
        {result['text']}
        """

        context_parts.append(
            clean_text(
                context
            )
        )

    return "\n\n".join(
        context_parts
    )

sample_rag_context = build_rag_context(
    complete_evidence
)


print(
    "RAG Context Length:",
    len(sample_rag_context)
)


print(
    "\nRAG CONTEXT PREVIEW:\n"
)


print(
    sample_rag_context[:8000]
)

import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )
else:
    print(
        "WARNING: No GPU detected. "
        "LLM generation will be very slow."
    )

import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig
)


LLM_MODEL_NAME = (
    "Qwen/Qwen2.5-3B-Instruct"
)


quantization_config = BitsAndBytesConfig(

    load_in_4bit=True,

    bnb_4bit_compute_dtype=torch.float16,

    bnb_4bit_quant_type="nf4",

    bnb_4bit_use_double_quant=True
)


tokenizer = AutoTokenizer.from_pretrained(
    LLM_MODEL_NAME
)


llm_model = AutoModelForCausalLM.from_pretrained(

    LLM_MODEL_NAME,

    quantization_config=quantization_config,

    device_map="auto"
)


print(
    "✓ Local Hugging Face LLM loaded successfully"
)

print(
    "Model:",
    LLM_MODEL_NAME
)

def select_llm_evidence(
    evidence_results,
    max_per_source=3,
    max_total=10
):

    selected = []

    # -----------------------------
    # Ensure source diversity
    # -----------------------------

    for source in [
        "BIS",
        "WHO",
        "CGWB"
    ]:

        source_results = [

            result

            for result in evidence_results

            if result["source_type"] == source

        ]


        source_results = sorted(

            source_results,

            key=lambda x: x[
                "similarity_score"
            ],

            reverse=True

        )


        selected.extend(

            source_results[
                :max_per_source
            ]

        )


    # -----------------------------
    # Deduplicate
    # -----------------------------

    selected = deduplicate_results(
        selected
    )


    # -----------------------------
    # Sort by relevance
    # -----------------------------

    selected = sorted(

        selected,

        key=lambda x: x[
            "similarity_score"
        ],

        reverse=True

    )


    return selected[
        :max_total
    ]

sample_llm_evidence = select_llm_evidence(

    complete_evidence,

    max_per_source=3,

    max_total=9

)


print(
    "Evidence chunks selected:",
    len(sample_llm_evidence)
)


for result in sample_llm_evidence:

    print(
        result["source_type"],
        "| Page:",
        result["page"],
        "| Score:",
        round(
            result["similarity_score"],
            4
        )
    )

def build_llm_context(
    evidence_results,
    max_chars_per_chunk=1800
):

    context_parts = []


    for i, result in enumerate(
        evidence_results,
        start=1
    ):

        evidence_text = result[
            "text"
        ][
            :max_chars_per_chunk
        ]


        context = f"""
REFERENCE {i}

Organization: {result['source_type']}

Document: {result['source']}

Page: {result['page']}

Evidence:
{evidence_text}
"""


        context_parts.append(
            clean_text(
                context
            )
        )


    return "\n\n".join(
        context_parts
    )

sample_llm_context = build_llm_context(
    sample_llm_evidence
)


print(
    "Context characters:",
    len(sample_llm_context)
)


print(
    "\nCONTEXT PREVIEW:\n"
)


print(
    sample_llm_context[:5000]
)

AGENT5_SYSTEM_PROMPT = """
You are Agent 5, an expert groundwater Policy Recommendation Agent.

Your task is to generate comprehensive and evidence-based
recommendations for groundwater heavy-metal contamination.

Your recommendations are intended for:

- Government authorities
- Environmental regulators
- Groundwater management agencies
- Public-health authorities
- Water-supply agencies
- Affected communities

Use ONLY the authoritative evidence supplied in the RAG context
for factual regulatory claims and supporting references.

The evidence may come from:

- WHO drinking-water guidelines
- BIS drinking-water standards and testing guidance
- CGWB groundwater quality reports

You may use general scientific reasoning to explain a recommendation,
but you must never invent:

- Regulatory limits
- Guideline values
- Removal percentages
- Document names
- Page numbers
- Government regulations
- Scientific findings

Do not treat HMPI risk categories as official WHO or BIS
regulatory classifications.

Consider the predicted HMPI as a model-generated risk indicator.

Recommendations must be specific to:

- Location
- Risk level
- Major pollutants
- Pollution source
- Prediction confidence
- Retrieved regulatory evidence

If evidence is insufficient to support a specific claim,
recommend verification against the applicable authoritative
standard instead of inventing information.

Generate detailed and actionable recommendations.

Return ONLY valid JSON.
"""

def create_local_llm_prompt(
    row,
    rag_context
):

    prompt = f"""
Generate an evidence-based groundwater policy recommendation
report for the following case.

==================================================
RISK ASSESSMENT
==================================================

Region ID:
{row['Region_ID']}

Location:
{row['District']}, {row['State']}

Coordinates:
Latitude {row['Latitude']}
Longitude {row['Longitude']}

Forecast Year:
{row['Forecast_Year']}

Predicted HMPI:
{row['Predicted_HMPI']}

Risk Level:
{row['Risk_Level']}

Risk Explanation:
{row['Risk_Explanation']}

Major Pollutants:
{row['Major_Pollutants']}

Pollution Source:
{row['Pollution_Source']}

Prediction Confidence:
{row['Confidence']}

Confidence Level:
{row['Confidence_Level']}


==================================================
AUTHORITATIVE RAG EVIDENCE
==================================================

{rag_context}


==================================================
INSTRUCTIONS
==================================================

Analyze the risk assessment together with the supplied
authoritative evidence.

Generate comprehensive recommendations covering all
major pollutants identified in the case.

IMMEDIATE ACTIONS REQUIRED:

Include actions necessary to immediately reduce potential
human exposure and verify the contamination situation.

Consider water testing, confirmation of pollutant concentrations,
identification of affected sources, temporary risk-management
measures, and communication with relevant authorities.

MITIGATION STRATEGIES:

Recommend appropriate source-control and water-treatment
approaches supported by the available evidence.

Consider the pollution source classification when recommending
mitigation.

For geogenic contamination, focus on managing naturally occurring
contaminants, source substitution where appropriate, treatment,
and long-term aquifer management.

For anthropogenic contamination, also consider pollution-source
identification and control.

For mixed contamination, address both pathways.

LONG-TERM MONITORING:

Provide recommendations for groundwater-quality monitoring,
trend analysis, seasonal monitoring where relevant, treatment
performance verification, and reassessment.

GOVERNMENT POLICY SUGGESTIONS:

Provide actionable recommendations for government agencies,
local authorities, groundwater agencies, environmental regulators,
and public-health authorities.

POSITIVE INDICATORS:

Identify measurable indicators that would demonstrate that
the intervention is working.

SUPPORTING REFERENCES:

Use ONLY references that appear in the RAG evidence.

For every reference include:

- Organization
- Document
- Page
- Relevance

Do not invent references.

==================================================
REQUIRED JSON OUTPUT
==================================================

Return ONLY valid JSON in this exact structure:

{{
  "Immediate_Actions_Required": [
    "Recommendation 1",
    "Recommendation 2"
  ],

  "Mitigation_Strategies": [
    "Strategy 1",
    "Strategy 2"
  ],

  "Long_Term_Monitoring": [
    "Recommendation 1",
    "Recommendation 2"
  ],

  "Government_Policy_Suggestions": [
    "Policy suggestion 1",
    "Policy suggestion 2"
  ],

  "Positive_Indicators": [
    "Indicator 1",
    "Indicator 2"
  ],

  "Supporting_References": [
    {{
      "Organization": "Organization name",
      "Document": "Document name",
      "Page": "Page number",
      "Relevance": "How this reference supports the recommendation"
    }}
  ]
}}

There is NO strict limit on the number of recommendations.

Provide as many recommendations as necessary for a
comprehensive response.

Do not omit an important recommendation simply to make
the response shorter.

Return JSON only.
"""

    return prompt

def generate_local_policy_recommendation(
    row,
    rag_context,
    max_new_tokens=1800
):

    user_prompt = create_local_llm_prompt(
        row,
        rag_context
    )


    messages = [

        {
            "role": "system",
            "content": AGENT5_SYSTEM_PROMPT
        },

        {
            "role": "user",
            "content": user_prompt
        }

    ]


    text = tokenizer.apply_chat_template(

        messages,

        tokenize=False,

        add_generation_prompt=True

    )


    model_inputs = tokenizer(

        [text],

        return_tensors="pt"

    ).to(
        llm_model.device
    )


    with torch.no_grad():

        generated_ids = llm_model.generate(

            **model_inputs,

            max_new_tokens=max_new_tokens,

            do_sample=False,

            repetition_penalty=1.05

        )


    # Remove input prompt tokens
    generated_ids = [

        output_ids[
            len(input_ids):
        ]

        for input_ids, output_ids in zip(

            model_inputs.input_ids,

            generated_ids

        )

    ]


    response = tokenizer.batch_decode(

        generated_ids,

        skip_special_tokens=True

    )[0]


    return response.strip()

sample_response = (
    generate_local_policy_recommendation(

        sample_row,

        sample_llm_context,

        max_new_tokens=1800

    )
)


print(
    sample_response
)

def clean_json_response(
    response
):

    response = response.strip()


    if response.startswith(
        "```json"
    ):

        response = response[
            7:
        ]


    elif response.startswith(
        "```"
    ):

        response = response[
            3:
        ]


    if response.endswith(
        "```"
    ):

        response = response[
            :-3
        ]


    return response.strip()

import json


cleaned_response = clean_json_response(
    sample_response
)


try:

    sample_recommendation = json.loads(
        cleaned_response
    )


    print(
        "✓ Valid JSON generated"
    )


    print(
        json.dumps(
            sample_recommendation,
            indent=2,
            ensure_ascii=False
        )
    )


except json.JSONDecodeError as e:

    print(
        "✗ Invalid JSON"
    )

    print(
        "Error:",
        e
    )

    print(
        "\nRaw response:\n"
    )

    print(
        sample_response
    )

REQUIRED_OUTPUT_KEYS = [
    "Immediate_Actions_Required",
    "Mitigation_Strategies",
    "Long_Term_Monitoring",
    "Government_Policy_Suggestions",
    "Positive_Indicators",
    "Supporting_References"
]


def validate_recommendation_json(data):

    if not isinstance(data, dict):
        return False

    for key in REQUIRED_OUTPUT_KEYS:

        if key not in data:
            return False

    return True

def process_agent5_row(
    row,
    max_retries=2
):

    # --------------------------------
    # Retrieve complete RAG evidence
    # --------------------------------

    evidence = retrieve_complete_evidence(
        row
    )


    # --------------------------------
    # Select strongest evidence
    # --------------------------------

    selected_evidence = select_llm_evidence(
        evidence,
        max_per_source=3,
        max_total=9
    )


    # --------------------------------
    # Build LLM context
    # --------------------------------

    rag_context = build_llm_context(
        selected_evidence
    )


    # --------------------------------
    # Generate recommendation
    # --------------------------------

    for attempt in range(
        max_retries
    ):

        try:

            response = (
                generate_local_policy_recommendation(
                    row,
                    rag_context,
                    max_new_tokens=1800
                )
            )


            cleaned_response = (
                clean_json_response(
                    response
                )
            )


            result = json.loads(
                cleaned_response
            )


            if validate_recommendation_json(
                result
            ):

                return {

                    "success": True,

                    "recommendation": result,

                    "evidence": selected_evidence

                }


        except Exception as e:

            print(
                f"Attempt {attempt + 1} failed:",
                str(e)
            )


    return {

        "success": False,

        "recommendation": None,

        "evidence": selected_evidence

    }

test_result = process_agent5_row(
    df.iloc[0]
)


print(
    "Success:",
    test_result["success"]
)


if test_result["success"]:

    print(

        json.dumps(

            test_result[
                "recommendation"
            ],

            indent=2,

            ensure_ascii=False

        )

    )

CHECKPOINT_FILE = (
    "/content/agent5_checkpoint.json"
)


FINAL_JSON_FILE = (
    "/content/agent5_final_output.json"
)


FINAL_CSV_FILE = (
    "/content/agent5_final_output.csv"
)

import time


all_results = []


for index, row in df.iterrows():

    print(
        "\n" + "=" * 80
    )

    print(
        f"Processing {index + 1}/{len(df)}"
    )

    print(
        "Region:",
        row["Region_ID"]
    )

    print(
        "Location:",
        row["District"],
        ",",
        row["State"]
    )


    result = process_agent5_row(
        row
    )


    output_record = {

        "Region_ID":
        row["Region_ID"],

        "State":
        row["State"],

        "District":
        row["District"],

        "Latitude":
        row["Latitude"],

        "Longitude":
        row["Longitude"],

        "Forecast_Year":
        row["Forecast_Year"],

        "Predicted_HMPI":
        row["Predicted_HMPI"],

        "Risk_Level":
        row["Risk_Level"],

        "Major_Pollutants":
        row["Major_Pollutants"],

        "Pollution_Source":
        row["Pollution_Source"],

        "Confidence":
        row["Confidence"],

        "Confidence_Level":
        row["Confidence_Level"],

        "Generation_Success":
        result["success"],

        "Recommendations":
        result["recommendation"]

    }


    all_results.append(
        output_record
    )


    # Save checkpoint
    with open(
        CHECKPOINT_FILE,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(

            all_results,

            f,

            indent=2,

            ensure_ascii=False,

            default=str

        )


    print(
        "Success:",
        result["success"]
    )

success_count = sum(

    1

    for result in all_results

    if result[
        "Generation_Success"
    ]

)


failure_count = (

    len(all_results)

    - success_count

)


print(
    "Total processed:",
    len(all_results)
)

print(
    "Successful:",
    success_count
)

print(
    "Failed:",
    failure_count
)

with open(
    FINAL_JSON_FILE,
    "w",
    encoding="utf-8"
) as f:

    json.dump(

        all_results,

        f,

        indent=2,

        ensure_ascii=False,

        default=str

    )


print(
    "✓ Final JSON saved:"
)

print(
    FINAL_JSON_FILE
)

csv_records = []


for record in all_results:

    recommendation = (
        record["Recommendations"]
        or {}
    )


    csv_record = {

        "Region_ID":
        record["Region_ID"],

        "State":
        record["State"],

        "District":
        record["District"],

        "Latitude":
        record["Latitude"],

        "Longitude":
        record["Longitude"],

        "Forecast_Year":
        record["Forecast_Year"],

        "Predicted_HMPI":
        record["Predicted_HMPI"],

        "Risk_Level":
        record["Risk_Level"],

        "Major_Pollutants":
        record["Major_Pollutants"],

        "Pollution_Source":
        record["Pollution_Source"],

        "Confidence":
        record["Confidence"],

        "Confidence_Level":
        record["Confidence_Level"],


        "Immediate_Actions_Required":

        json.dumps(

            recommendation.get(
                "Immediate_Actions_Required",
                []
            ),

            ensure_ascii=False

        ),


        "Mitigation_Strategies":

        json.dumps(

            recommendation.get(
                "Mitigation_Strategies",
                []
            ),

            ensure_ascii=False

        ),


        "Long_Term_Monitoring":

        json.dumps(

            recommendation.get(
                "Long_Term_Monitoring",
                []
            ),

            ensure_ascii=False

        ),


        "Government_Policy_Suggestions":

        json.dumps(

            recommendation.get(
                "Government_Policy_Suggestions",
                []
            ),

            ensure_ascii=False

        ),


        "Positive_Indicators":

        json.dumps(

            recommendation.get(
                "Positive_Indicators",
                []
            ),

            ensure_ascii=False

        ),


        "Supporting_References":

        json.dumps(

            recommendation.get(
                "Supporting_References",
                []
            ),

            ensure_ascii=False

        ),


        "Generation_Success":

        record[
            "Generation_Success"
        ]

    }


    csv_records.append(
        csv_record
    )


final_df = pd.DataFrame(
    csv_records
)


final_df.to_csv(

    FINAL_CSV_FILE,

    index=False

)


print(
    "✓ Final CSV saved"
)

print(
    "Shape:",
    final_df.shape
)


display(
    final_df.head()
)

