# -*- coding: utf-8 -*-
"""Agent_forcast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aopKtrBeS8_BDY8UD1q9nYP58-nt0ph4
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader

import joblib
import os
import random

# Reproducibility
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device :", device)

df = pd.read_csv("groundwater_regional_timeseries.csv")
print("Dataset Shape :", df.shape)
df.head()

print("="*60)
print(df.info())

print("="*60)
print(df.describe())

print("="*60)
print("Missing Values")
print(df.isnull().sum())

print("="*60)
print("Duplicate Rows :", df.duplicated().sum())

df.columns = (

    df.columns
      .str.strip()
      .str.replace(" ", "_")
      .str.replace("(", "", regex=False)
      .str.replace(")", "", regex=False)
      .str.replace("/", "_", regex=False)

)

print(df.columns.tolist())

required_columns = [

    "Region_ID",
    "Year",

    "Latitude",
    "Longitude",

    "pH",
    "EC_uScm",
    "TDS_mgL",

    "Iron_Fe_mgL",
    "Arsenic_As_mgL",
    "Lead_Pb_mgL",
    "Cadmium_Cd_mgL",
    "Chromium_Cr_mgL",
    "Mercury_Hg_mgL",
    "Nickel_Ni_mgL",
    "Copper_Cu_mgL",
    "Zinc_Zn_mgL",
    "Manganese_Mn_mgL",
    "Selenium_Se_mgL",

    "HMPI"

]

missing = [col for col in required_columns if col not in df.columns]

if len(missing)==0:

    print("All required columns found.")

else:

    print("Missing Columns")

    print(missing)

df = df.sort_values(

    ["Region_ID","Year"]

).reset_index(drop=True)

df.head()

numeric_columns = df.select_dtypes(include=np.number).columns

imputer = SimpleImputer(strategy="median")

df[numeric_columns] = imputer.fit_transform(
    df[numeric_columns]
)

joblib.dump(

    imputer,

    "median_imputer.pkl"

)

print("Remaining Missing Values")

print(df.isnull().sum().sum())

categorical_columns = df.select_dtypes(include="object").columns.tolist()

print(categorical_columns)

encoders = {}

for col in categorical_columns:

    encoder = LabelEncoder()

    df[col] = encoder.fit_transform(df[col].astype(str))

    encoders[col] = encoder

joblib.dump(

    encoders,

    "label_encoders.pkl"

)

print("Encoding Completed")

#############################################
# Heavy Metals
#############################################

HEAVY_METAL_COLUMNS = [

    "Iron_Fe_mgL",
    "Arsenic_As_mgL",
    "Lead_Pb_mgL",
    "Cadmium_Cd_mgL",
    "Chromium_Cr_mgL",
    "Mercury_Hg_mgL",
    "Nickel_Ni_mgL",
    "Copper_Cu_mgL",
    "Zinc_Zn_mgL",
    "Manganese_Mn_mgL",
    "Selenium_Se_mgL"

]

#############################################
# Target Columns
#############################################

TARGET_COLUMNS = HEAVY_METAL_COLUMNS + [

    "HMPI"

]

#############################################
# Sequence Length
#############################################

SEQUENCE_LENGTH = 6

INPUT_COLUMNS = [

    "Latitude",
    "Longitude",
    "pH",

    "EC_uScm",

    "TDS_mgL",

    "Turbidity_NTU",

    "Temperature_C",

    "Dissolved_Oxygen_mgL",

    "Hardness_mgL",

    "Alkalinity_mgL",

    "Calcium_mgL",

    "Magnesium_mgL",

    "Chloride_mgL",

    "Sulphate_mgL",

    "Nitrate_mgL",

    "Fluoride_mgL"

] + HEAVY_METAL_COLUMNS

print("Number of Input Features :", len(INPUT_COLUMNS))

print(INPUT_COLUMNS)

#############################################
# Preserve Region IDs
#############################################

original_region_ids = df["Region_ID"].copy()

print("Total Regions :", original_region_ids.nunique())

#############################################
# Feature Scaling
#############################################

feature_scaler = StandardScaler()
target_scaler = StandardScaler()

X_scaled = feature_scaler.fit_transform(
    df[INPUT_COLUMNS]
)

Y_scaled = target_scaler.fit_transform(
    df[TARGET_COLUMNS]
)

joblib.dump(feature_scaler, "feature_scaler.pkl")
joblib.dump(target_scaler, "target_scaler.pkl")

scaled_df = pd.DataFrame(
    X_scaled,
    columns=INPUT_COLUMNS
)

for i, col in enumerate(TARGET_COLUMNS):
    scaled_df["TARGET_" + col] = Y_scaled[:, i]

scaled_df["Region_ID"] = original_region_ids.values
scaled_df["Year"] = df["Year"].values

scaled_df.head()

region_counts = scaled_df.groupby("Region_ID").size()

print(region_counts.describe())

print()

print("Minimum Years :", region_counts.min())

print("Maximum Years :", region_counts.max())

#############################################
# Sequence Generation
#############################################

X_sequences = []
Y_sequences = []

for region in scaled_df["Region_ID"].unique():

    region_df = scaled_df[
        scaled_df["Region_ID"] == region
    ].sort_values("Year")

    feature_values = region_df[INPUT_COLUMNS].values

    target_values = region_df[
        ["TARGET_" + col for col in TARGET_COLUMNS]
    ].values

    for i in range(len(region_df) - SEQUENCE_LENGTH):

        X_sequences.append(
            feature_values[
                i : i + SEQUENCE_LENGTH
            ]
        )

        Y_sequences.append(
            target_values[
                i + SEQUENCE_LENGTH
            ]
        )

X_sequences = np.array(X_sequences)
Y_sequences = np.array(Y_sequences)

print("X Shape :", X_sequences.shape)
print("Y Shape :", Y_sequences.shape)

#############################################
# Split by Region
#############################################

from sklearn.model_selection import train_test_split

regions = sorted(df["Region_ID"].unique())

train_regions, temp_regions = train_test_split(
    regions,
    test_size=0.30,
    random_state=42
)

val_regions, test_regions = train_test_split(
    temp_regions,
    test_size=0.50,
    random_state=42
)

print("Train Regions :", len(train_regions))
print("Validation Regions :", len(val_regions))
print("Test Regions :", len(test_regions))

#############################################
# Sequence Generator
#############################################

def create_sequences(region_list):

    X_sequences = []
    Y_sequences = []

    for region in region_list:

        region_df = scaled_df[
            scaled_df["Region_ID"] == region
        ].sort_values("Year")

        if len(region_df) <= SEQUENCE_LENGTH:
            continue

        feature_values = region_df[
            INPUT_COLUMNS
        ].values

        target_values = region_df[
            ["TARGET_" + c for c in TARGET_COLUMNS]
        ].values

        for i in range(
            len(region_df) - SEQUENCE_LENGTH
        ):

            X_sequences.append(
                feature_values[
                    i:i+SEQUENCE_LENGTH
                ]
            )

            Y_sequences.append(
                target_values[
                    i+SEQUENCE_LENGTH
                ]
            )

    return np.array(X_sequences), np.array(Y_sequences)

#############################################
# Generate Sequences
#############################################

X_train, y_train = create_sequences(
    train_regions
)

X_val, y_val = create_sequences(
    val_regions
)

X_test, y_test = create_sequences(
    test_regions
)

print("Train :", X_train.shape)

print("Validation :", X_val.shape)

print("Test :", X_test.shape)

X_train = torch.FloatTensor(X_train)
X_val = torch.FloatTensor(X_val)
X_test = torch.FloatTensor(X_test)

y_train = torch.FloatTensor(y_train)
y_val = torch.FloatTensor(y_val)
y_test = torch.FloatTensor(y_test)

print(X_train.shape)
print(y_train.shape)

class GroundwaterDataset(Dataset):

    def __init__(self, X, y):

        self.X = X
        self.y = y

    def __len__(self):

        return len(self.X)

    def __getitem__(self, idx):

        return self.X[idx], self.y[idx]

BATCH_SIZE = 32

train_dataset = GroundwaterDataset(
    X_train,
    y_train
)

val_dataset = GroundwaterDataset(
    X_val,
    y_val
)

test_dataset = GroundwaterDataset(
    X_test,
    y_test
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("Train Batches :", len(train_loader))
print("Validation Batches :", len(val_loader))
print("Test Batches :", len(test_loader))

class MultiHeadTemporalAttention(nn.Module):

    def __init__(self, embed_dim):

        super().__init__()

        self.attn = nn.MultiheadAttention(

            embed_dim=embed_dim,

            num_heads=4,

            batch_first=True,

            dropout=0.1

        )

        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x):

        attn_output, _ = self.attn(

            x,

            x,

            x

        )

        x = self.norm(

            x + attn_output

        )

        return x.mean(dim=1)

class GroundwaterBiLSTM(nn.Module):

    def __init__(self):

        super().__init__()

        input_size = len(INPUT_COLUMNS)

        ########################################

        self.lstm1 = nn.LSTM(
            input_size=input_size,
            hidden_size=64, # Changed from 96 to 64
            batch_first=True,
            bidirectional=True
        )

        self.norm1 = nn.LayerNorm(128)

        self.dropout1 = nn.Dropout(0.15)

        ########################################

        self.lstm2 = nn.LSTM(
            input_size=128,
            hidden_size=32, # Changed from 48 to 32
            batch_first=True,
            bidirectional=True
        )

        self.norm2 = nn.LayerNorm(64)

        self.dropout2 = nn.Dropout(0.15)

        ########################################

        # Assuming 'Attention' refers to 'MultiHeadTemporalAttention'
        self.attention = MultiHeadTemporalAttention(64) # Changed from Attention(32) to MultiHeadTemporalAttention(64)

        ########################################

        self.fc1 = nn.Linear(64,64)

        self.fc2 = nn.Linear(64,64)

        self.norm = nn.LayerNorm(64)

        self.dropout = nn.Dropout(0.15)

        ########################################
        # Heavy Metal Head
        ########################################

        self.metal_head = nn.Sequential(

            nn.Linear(64,32),

            nn.ReLU(),

            nn.Linear(32,11)

        )

        ########################################
        # HMPI Head
        ########################################

        self.hmpi_head = nn.Sequential(

            nn.Linear(64,16),

            nn.ReLU(),

            nn.Linear(16,1)

        )

    def forward(self,x):

        x,_ = self.lstm1(x)

        x = self.norm1(x)

        x = self.dropout1(x)

        x,_ = self.lstm2(x)

        x = self.norm2(x)

        x = self.dropout2(x)

        x = self.attention(x)

        identity = x
        x = torch.relu(

    self.fc1(x)

)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.norm(

    x + identity

)
        metals = self.metal_head(x)
        hmpi = self.hmpi_head(x)

        return torch.cat(

            [

                metals,

                hmpi

            ],

            dim=1

        )

model = GroundwaterBiLSTM().to(device)
print(model)

#############################################
# Xavier Initialization
#############################################

def initialize_weights(model):

    for name, param in model.named_parameters():

        if "weight" in name:

            if param.dim() > 1:

                nn.init.xavier_uniform_(param)

        elif "bias" in name:

            nn.init.constant_(param, 0)

initialize_weights(model)

print("Weights Initialized")

criterion = nn.SmoothL1Loss(
    beta=1.0
)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=0.0005,
    weight_decay=5e-5
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(

    optimizer,

    mode="min",

    factor=0.5,

    patience=8

)

best_loss = np.inf
patience = 20
counter = 0
EPOCHS = 100
train_losses = []
val_losses = []

#############################################
# Mixed Precision
#############################################

scaler = torch.cuda.amp.GradScaler(
    enabled=torch.cuda.is_available()
)

#############################################
# Gradient Accumulation
#############################################

ACCUMULATION_STEPS = 2

#############################################
# Training
#############################################

best_loss = np.inf

counter = 0

train_losses = []

val_losses = []

for epoch in range(EPOCHS):

    ######################################

    model.train()

    running_loss = 0

    optimizer.zero_grad()

    ######################################

    for step, (X_batch, y_batch) in enumerate(train_loader):

        X_batch = X_batch.to(device)

        y_batch = y_batch.to(device)

        ##################################

        with torch.cuda.amp.autocast(
            enabled=torch.cuda.is_available()
        ):

            predictions = model(X_batch)

            metal_pred = predictions[:, :11]
            hmpi_pred = predictions[:, 11:]
            metal_true = y_batch[:, :11]
            hmpi_true = y_batch[:, 11:]
            loss_metals = criterion(
                metal_pred,
                metal_true
)
            loss_hmpi = criterion(
    hmpi_pred,
    hmpi_true
)
            loss = 0.6 * loss_metals + 0.4 * loss_hmpi
            loss = loss / ACCUMULATION_STEPS

        ##################################

        scaler.scale(loss).backward()

        ##################################

        if (

            (step + 1) % ACCUMULATION_STEPS == 0

            or

            (step + 1) == len(train_loader)

        ):

            scaler.unscale_(optimizer)

            torch.nn.utils.clip_grad_norm_(

                model.parameters(),

                max_norm=1.0

            )

            scaler.step(optimizer)

            scaler.update()

            optimizer.zero_grad()

        ##################################

        running_loss += (

            loss.item()

            * ACCUMULATION_STEPS

        )

    ######################################

    train_loss = running_loss / len(train_loader)

    train_losses.append(train_loss)

    ######################################
    # Validation
    ######################################

    model.eval()

    running_val = 0

    with torch.no_grad():

        for X_batch, y_batch in val_loader:

            X_batch = X_batch.to(device)

            y_batch = y_batch.to(device)

            predictions = model(X_batch)

            metal_pred = predictions[:, :11]
            hmpi_pred = predictions[:, 11:]
            metal_true = y_batch[:, :11]
            hmpi_true = y_batch[:, 11:]
            loss_metals = criterion(
    metal_pred,
    metal_true
)
            loss_hmpi = criterion(
    hmpi_pred,
    hmpi_true
)
            loss = 0.7 * loss_metals + 0.3 * loss_hmpi
            loss = loss / ACCUMULATION_STEPS

            running_val += loss.item()

    ######################################

    val_loss = running_val / len(val_loader)

    val_losses.append(val_loss)

    ######################################

    scheduler.step(val_loss)

    ######################################

    print(

        f"Epoch {epoch+1}/{EPOCHS}"

        f" | Train:{train_loss:.5f}"

        f" | Validation:{val_loss:.5f}"

    )

    ######################################
    # Save Best Model
    ######################################

    if val_loss < best_loss:

        best_loss = val_loss

        counter = 0

        torch.save(

            {

                "epoch": epoch,

                "model_state_dict": model.state_dict(),

                "optimizer_state_dict": optimizer.state_dict(),

                "validation_loss": val_loss

            },

            "best_groundwater_model.pth"

        )

    else:

        counter += 1

        if counter >= patience:

            print()

            print("Early Stopping Triggered")

            break

#############################################
# Load Best Model
#############################################

checkpoint = torch.load(

    "best_groundwater_model.pth",

    map_location=device

)

model.load_state_dict(

    checkpoint["model_state_dict"]

)

print()

print("Best Epoch :", checkpoint["epoch"] + 1)

print("Validation Loss :", checkpoint["validation_loss"])

#############################################
# Loss Curves
#############################################

plt.figure(

    figsize=(10,5)

)

plt.plot(

    train_losses,

    label="Training Loss",

    linewidth=2

)

plt.plot(

    val_losses,

    label="Validation Loss",

    linewidth=2

)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.grid(True)

plt.legend()

plt.show()

#############################################
# Evaluation Metrics
#############################################

from sklearn.metrics import (

    mean_absolute_error,

    mean_squared_error,

    r2_score,

    explained_variance_score,

    mean_absolute_percentage_error

)

#############################################
# Predictions
#############################################

model.eval()

predictions = []
actuals = []

with torch.no_grad():

    for X_batch, y_batch in test_loader:

        X_batch = X_batch.to(device)

        outputs = model(X_batch)

        predictions.extend(
            outputs.cpu().numpy()
        )

        actuals.extend(
            y_batch.numpy()
        )

predictions = np.array(predictions)

actuals = np.array(actuals)

print(predictions.shape)

#############################################
# Inverse Scaling
#############################################

predictions = target_scaler.inverse_transform(
    predictions
)

actuals = target_scaler.inverse_transform(
    actuals
)

print(predictions[:3])

#############################################
# Overall Metrics
#############################################

rmse = np.sqrt(

    mean_squared_error(

        actuals,

        predictions

    )

)

mae = mean_absolute_error(

    actuals,

    predictions

)

r2 = r2_score(

    actuals,

    predictions

)

evs = explained_variance_score(

    actuals,

    predictions

)

mape = mean_absolute_percentage_error(

    actuals,

    predictions

)

print("="*50)

print(f"RMSE : {rmse:.4f}")

print(f"MAE  : {mae:.4f}")

print(f"R²   : {r2:.4f}")

print(f"Explained Variance : {evs:.4f}")

print(f"MAPE : {mape:.4f}")

print("="*50)

hmpi_index = TARGET_COLUMNS.index("HMPI")
corr = np.corrcoef(
    actuals[:, hmpi_index],
    predictions[:, hmpi_index]
)[0,1]

print(f"HMPI Correlation : {corr:.4f}")

#############################################
# Per Target Evaluation
#############################################

metrics = []

for i, target in enumerate(TARGET_COLUMNS):

    mae = mean_absolute_error(

        actuals[:,i],

        predictions[:,i]

    )

    rmse = np.sqrt(

        mean_squared_error(

            actuals[:,i],

            predictions[:,i]

        )

    )

    r2 = r2_score(

        actuals[:,i],

        predictions[:,i]

    )

    metrics.append([

        target,

        mae,

        rmse,

        r2

    ])

metrics_df = pd.DataFrame(

    metrics,

    columns=[

        "Target",

        "MAE",

        "RMSE",

        "R2"

    ]

)

metrics_df

#############################################
# HMPI Prediction
#############################################

hmpi_index = TARGET_COLUMNS.index("HMPI")

plt.figure(figsize=(8,6))

plt.scatter(

    actuals[:,hmpi_index],

    predictions[:,hmpi_index],

    alpha=0.7

)

minimum = min(

    actuals[:,hmpi_index].min(),

    predictions[:,hmpi_index].min()

)

maximum = max(

    actuals[:,hmpi_index].max(),

    predictions[:,hmpi_index].max()

)

plt.plot(

    [minimum,maximum],

    [minimum,maximum],

    'r--'

)

plt.xlabel("Actual HMPI")

plt.ylabel("Predicted HMPI")

plt.title("HMPI Prediction")

plt.grid(True)

plt.show()

for region in df["Region_ID"].unique()[:5]:

    temp = df[df["Region_ID"] == region].sort_values("Year")

    plt.figure(figsize=(6,3))
    plt.plot(temp["Year"], temp["HMPI"], marker="o")
    plt.title(region)
    plt.grid(True)
    plt.show()

###################################################
# Future Prediction DataFrame
###################################################

future_df = pd.DataFrame(
    predictions,
    columns=TARGET_COLUMNS
)

future_df.head()

###################################################
# WHO / BIS Permissible Limits (mg/L)
###################################################

limits = {

    "Iron_Fe_mgL":0.30,

    "Arsenic_As_mgL":0.01,

    "Lead_Pb_mgL":0.01,

    "Cadmium_Cd_mgL":0.003,

    "Chromium_Cr_mgL":0.05,

    "Mercury_Hg_mgL":0.001,

    "Nickel_Ni_mgL":0.02,

    "Copper_Cu_mgL":0.05,

    "Zinc_Zn_mgL":3.0,

    "Manganese_Mn_mgL":0.10,

    "Selenium_Se_mgL":0.01

}

###################################################
# Contamination Factor
###################################################

for metal in HEAVY_METAL_COLUMNS:

    future_df["CF_"+metal] = (

        future_df[metal]

        /

        limits[metal]

    )

future_df.head()

###################################################
# Average CF
###################################################

cf_columns = [

    c

    for c in future_df.columns

    if c.startswith("CF_")

]

future_df["Average_CF"] = future_df[cf_columns].mean(axis=1)

future_df.head()

###################################################
# Pollution Load Index
###################################################

future_df["PLI"] = np.power(

    future_df[cf_columns].prod(axis=1),

    1/len(cf_columns)

)

future_df.head()

###################################################
# Toxic Metal Count
###################################################

future_df["Toxic_Count"] = 0

for metal in HEAVY_METAL_COLUMNS:

    future_df["Toxic_Count"] += (

        future_df[metal]

        >

        limits[metal]

    ).astype(int)

future_df.head()

###################################################
# Natural Metal Count
###################################################

future_df["Natural_Count"] = (

    len(HEAVY_METAL_COLUMNS)

    -

    future_df["Toxic_Count"]

)

future_df.head()

future_df["Max_CF"] = future_df[cf_columns].max(axis=1)

future_df["Dominant_Metal"] = (

    future_df[cf_columns]

    .idxmax(axis=1)

)

###################################################
# Weighted Toxicity
###################################################

future_df["Weighted_Toxicity"] = future_df[cf_columns].sum(axis=1)

future_df.head()

###################################################
# Pollution Score
###################################################

future_df["Pollution_Score"] = (

      0.40 * future_df["HMPI"]

    + 0.30 * future_df["Average_CF"]

    + 0.30 * future_df["PLI"]

)

future_df.head()

###################################################
# Encode Dominant Metal
###################################################

from sklearn.preprocessing import LabelEncoder

dominant_encoder = LabelEncoder()

future_df["Dominant_Metal_Encoded"] = dominant_encoder.fit_transform(

    future_df["Dominant_Metal"]

)

future_df.head()

###################################################
# Final Features
###################################################

engineered_features = [

    "HMPI",

    "Average_CF",

    "PLI",

    "Toxic_Count",

    "Natural_Count",

    "Weighted_Toxicity",

    "Max_CF",

    "Pollution_Score",

    "Dominant_Metal_Encoded"

]

print(engineered_features)

###################################################
# Correlation Matrix
###################################################

plt.figure(figsize=(10,8))

sns.heatmap(

    future_df[engineered_features]

    .corr(),

    annot=True,

    cmap="viridis",

    fmt=".2f"

)

plt.title("Engineered Feature Correlation")

plt.show()

future_df["Dominant_Metal"].value_counts()

###################################################
# Features for PCA
###################################################

PCA_FEATURES = [

    "HMPI",

    "Average_CF",

    "PLI",

    "Max_CF",

    "Dominant_Metal_Encoded"

]

X_pca = future_df[PCA_FEATURES].copy()

X_pca.head()

###################################################
# Standardize Features
###################################################

from sklearn.preprocessing import StandardScaler

pca_scaler = StandardScaler()

X_scaled = pca_scaler.fit_transform(X_pca)

joblib.dump(
    pca_scaler,
    "pca_scaler.pkl"
)

print(X_scaled.shape)

###################################################
# PCA
###################################################

from sklearn.decomposition import PCA

pca = PCA(
    n_components=0.95,
    random_state=42
)

X_pca_transformed = pca.fit_transform(X_scaled)

joblib.dump(
    pca,
    "pca_model.pkl"
)

print("Original Shape :", X_scaled.shape)
print("Reduced Shape :", X_pca_transformed.shape)

###################################################
# Explained Variance
###################################################

plt.figure(figsize=(8,5))

plt.plot(

    np.cumsum(
        pca.explained_variance_ratio_
    ),

    marker="o"

)

plt.xlabel("Principal Components")

plt.ylabel("Cumulative Explained Variance")

plt.grid(True)

plt.show()

###################################################
# PCA Component Loadings
###################################################

loadings = pd.DataFrame(

    pca.components_.T,

    columns=[

        f"PC{i+1}"

        for i in range(
            pca.n_components_
        )

    ],

    index=PCA_FEATURES

)

loadings

###################################################
# PCA Scatter Plot
###################################################

plt.figure(figsize=(8,6))

plt.scatter(

    X_pca_transformed[:,0],

    X_pca_transformed[:,1],

    alpha=0.7

)

plt.xlabel("Principal Component 1")

plt.ylabel("Principal Component 2")

plt.title("Groundwater Samples after PCA")

plt.grid(True)

plt.show()

###################################################
# Elbow Method
###################################################

from sklearn.cluster import KMeans

inertia = []

K = range(2,11)

for k in K:

    kmeans = KMeans(

        n_clusters=k,

        random_state=42,

        n_init=20

    )

    kmeans.fit(X_pca_transformed)

    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))

plt.plot(

    K,

    inertia,

    marker="o"

)

plt.xlabel("Number of Clusters")

plt.ylabel("Inertia")

plt.title("Elbow Method")

plt.grid(True)

plt.show()

###################################################
# Silhouette Score
###################################################

from sklearn.metrics import silhouette_score

silhouette_scores = []

for k in K:

    model = KMeans(

        n_clusters=k,

        random_state=42,

        n_init=20

    )

    labels = model.fit_predict(

        X_pca_transformed

    )

    score = silhouette_score(

        X_pca_transformed,

        labels

    )

    silhouette_scores.append(score)

plt.figure(figsize=(8,5))

plt.plot(

    K,

    silhouette_scores,

    marker="o"

)

plt.xlabel("Number of Clusters")

plt.ylabel("Silhouette Score")

plt.title("Silhouette Analysis")

plt.grid(True)

plt.show()

best_k = K[
    np.argmax(silhouette_scores)
]

print("Best K :", best_k)

###################################################
# Final KMeans
###################################################

OPTIMAL_K = 7

kmeans = KMeans(

    n_clusters=OPTIMAL_K,

    random_state=42,

    n_init=20

)

future_df["Pollution_Cluster"] = kmeans.fit_predict(
    X_pca_transformed
)

joblib.dump(
    kmeans,
    "kmeans_model.pkl"
)

future_df.head()

###################################################
# Cluster Distribution
###################################################

cluster_counts = future_df["Pollution_Cluster"].value_counts().sort_index()

print(cluster_counts)

plt.figure(figsize=(8,5))

cluster_counts.plot(

    kind="bar"

)

plt.xlabel("Cluster")

plt.ylabel("Samples")

plt.title("Pollution Pattern Distribution")

plt.grid(axis="y")

plt.show()

###################################################
# Cluster Visualization
###################################################

plt.figure(figsize=(9,7))

scatter = plt.scatter(

    X_pca_transformed[:,0],

    X_pca_transformed[:,1],

    c=future_df["Pollution_Cluster"],

    cmap="tab10",

    s=60

)

plt.xlabel("PC1")

plt.ylabel("PC2")

plt.title("Pollution Pattern Discovery")

plt.colorbar(scatter,label="Cluster")

plt.grid(True)

plt.show()

###################################################
# Cluster Statistics
###################################################

cluster_summary = future_df.groupby(

    "Pollution_Cluster"

)[

    [

        "HMPI",

        "Average_CF",

        "PLI",

        "Max_CF",

        "Weighted_Toxicity"

    ]

].mean()

cluster_summary

###################################################
# Pollution Pattern Names
###################################################

cluster_names = {}

overall_hmpi = future_df["HMPI"].mean()
overall_cf = future_df["Average_CF"].mean()

for cluster in cluster_summary.index:

    hmpi = cluster_summary.loc[cluster, "HMPI"]
    cf = cluster_summary.loc[cluster, "Average_CF"]

    if hmpi > overall_hmpi and cf > overall_cf:
        name = "High Pollution"

    elif hmpi > overall_hmpi:
        name = "HMPI Dominant"

    elif cf > overall_cf:
        name = "Metal Contamination"

    else:
        name = "Low Pollution"

    cluster_names[cluster] = name

future_df["Pollution_Pattern"] = future_df[
    "Pollution_Cluster"
].map(cluster_names)

future_df.head()

###################################################
# Pollution Source Scoring Engine
###################################################

future_df["Anthro_Score"] = 0
future_df["Geo_Score"] = 0

###################################################
# HMPI Score
###################################################

future_df.loc[
    future_df["HMPI"] >= future_df["HMPI"].quantile(0.75),
    "Anthro_Score"
] += 2

future_df.loc[
    future_df["HMPI"] <= future_df["HMPI"].quantile(0.25),
    "Geo_Score"
] += 2

###################################################
# Average CF Score
###################################################

future_df.loc[
    future_df["Average_CF"] >= future_df["Average_CF"].quantile(0.75),
    "Anthro_Score"
] += 2

future_df.loc[
    future_df["Average_CF"] <= future_df["Average_CF"].quantile(0.25),
    "Geo_Score"
] += 2

###################################################
# PLI Score
###################################################

future_df.loc[
    future_df["PLI"] >= future_df["PLI"].quantile(0.75),
    "Anthro_Score"
] += 1

future_df.loc[
    future_df["PLI"] <= future_df["PLI"].quantile(0.25),
    "Geo_Score"
] += 1

###################################################
# Dominant Metal Score
###################################################

anthro_metals = [

    "CF_Copper_Cu_mgL",
    "CF_Lead_Pb_mgL",
    "CF_Cadmium_Cd_mgL",
    "CF_Chromium_Cr_mgL",
    "CF_Arsenic_As_mgL",
    "CF_Nickel_Ni_mgL",
    "CF_Mercury_Hg_mgL"

]

geo_metals = [

    "CF_Iron_Fe_mgL",
    "CF_Manganese_Mn_mgL"

]

future_df.loc[
    future_df["Dominant_Metal"].isin(anthro_metals),
    "Anthro_Score"
] += 2

future_df.loc[
    future_df["Dominant_Metal"].isin(geo_metals),
    "Geo_Score"
] += 2

###################################################
# Cluster-based Score
###################################################

high_clusters = cluster_summary.sort_values(

    "HMPI",

    ascending=False

).head(2).index

low_clusters = cluster_summary.sort_values(

    "HMPI",

    ascending=True

).head(2).index

future_df.loc[
    future_df["Pollution_Cluster"].isin(high_clusters),
    "Anthro_Score"
] += 1

future_df.loc[
    future_df["Pollution_Cluster"].isin(low_clusters),
    "Geo_Score"
] += 1

###################################################
# Final Pollution Source
###################################################

future_df["Pollution_Source"] = "Mixed"

difference = (

    future_df["Anthro_Score"]

    -

    future_df["Geo_Score"]

)

future_df.loc[
    difference >= 2,
    "Pollution_Source"
] = "Anthropogenic"

future_df.loc[
    difference <= -2,
    "Pollution_Source"
] = "Geogenic"

###################################################
# Distribution
###################################################

print(future_df["Pollution_Source"].value_counts())

future_df["Pollution_Source"].value_counts().plot(

    kind="bar",

    figsize=(7,5)

)

plt.grid(axis="y")

plt.show()

pd.crosstab(

    future_df["Pollution_Cluster"],

    future_df["Pollution_Source"]

)

###################################################
# Random Forest Dataset
###################################################

RF_FEATURES = [

    "Iron_Fe_mgL",
    "Arsenic_As_mgL",
    "Lead_Pb_mgL",
    "Cadmium_Cd_mgL",
    "Chromium_Cr_mgL",
    "Mercury_Hg_mgL",
    "Nickel_Ni_mgL",
    "Copper_Cu_mgL",
    "Zinc_Zn_mgL",
    "Manganese_Mn_mgL",
    "Selenium_Se_mgL",

    "HMPI",

    "Average_CF",

    "PLI",

    "Max_CF",

    "Weighted_Toxicity",

    "Dominant_Metal_Encoded",

    "Pollution_Cluster"

]

X = future_df[RF_FEATURES]

y = future_df["Pollution_Source"]

print(X.shape)
print(y.shape)

X.head()

###################################################
# Train Test Split
###################################################

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

print(X_train.shape)
print(X_test.shape)

###################################################
# Train Random Forest
###################################################

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(

    n_estimators=300,

    max_depth=8,

    min_samples_leaf=3,

    random_state=42,

    class_weight="balanced"

)

rf.fit(

    X_train,

    y_train

)

###################################################
# Predictions
###################################################
predictions = rf.predict(X_test)
probabilities = rf.predict_proba(X_test)

###################################################
# Evaluation
###################################################

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(

    "Accuracy :",

    accuracy_score(

        y_test,

        predictions

    )

)

print()

print(

    classification_report(

        y_test,

        predictions

    )

)

###################################################
# Confusion Matrix
###################################################

import seaborn as sns

cm = confusion_matrix(

    y_test,

    predictions,

    labels=rf.classes_

)

plt.figure(figsize=(7,6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=rf.classes_,
    yticklabels=rf.classes_
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Pollution Source Confusion Matrix")
plt.show()

###################################################
# Feature Importance
###################################################

importance = pd.DataFrame({

    "Feature":RF_FEATURES,

    "Importance":rf.feature_importances_

})

importance = importance.sort_values(

    "Importance",

    ascending=False

)

importance

###################################################
# Source Confidence Score
###################################################

future_df["Predicted_Source"] = rf.predict(

    X

)

future_df["Confidence"] = np.max(

    rf.predict_proba(X),

    axis=1

)

future_df[

    [

        "Predicted_Source",

        "Confidence"

    ]

].head()

###################################################
# Save Complete Agent 3 Pipeline
###################################################

import joblib

# Re-initialize the model to ensure it's the LSTM model
model = GroundwaterBiLSTM().to(device)

# Load best LSTM weights
# The saved file is a checkpoint containing 'model_state_dict', so we need to extract it
checkpoint = torch.load(
    "best_groundwater_model.pth", # Changed to best_groundwater_model.pth
    map_location="cpu"
)
model.load_state_dict(
    checkpoint["model_state_dict"]
)

model.eval()

# Define source_encoder as it's used in the pipeline
source_encoder = LabelEncoder()
source_encoder.fit(future_df["Pollution_Source"])

# Define FEATURE_COLUMNS as it's used in the pipeline
FEATURE_COLUMNS = INPUT_COLUMNS

pipeline = {

    ###################################################
    # Deep Learning Model
    ###################################################

    "lstm_model": model,

    ###################################################
    # Scalers
    ###################################################

    "feature_scaler": feature_scaler,

    "target_scaler": target_scaler,

    "pca_scaler": pca_scaler,

    ###################################################
    # PCA
    ###################################################

    "pca_model": pca,

    ###################################################
    # Clustering
    ###################################################

    "kmeans_model": kmeans,

    ###################################################
    # Random Forest
    ###################################################

    "random_forest": rf,

    ###################################################
    # Encoders
    ###################################################

    "dominant_encoder": dominant_encoder,

    "pollution_source_encoder": source_encoder,

    ###################################################
    # Metadata
    ###################################################

    "sequence_length": SEQUENCE_LENGTH,

    "forecast_features": FEATURE_COLUMNS,

    "forecast_targets": TARGET_COLUMNS,

    "rf_features": RF_FEATURES,

    "pca_features": PCA_FEATURES,

    "cf_columns": cf_columns,

    "limits": limits,

    "device": "cpu"

}

joblib.dump(

    pipeline,

    "agent3_complete_pipeline.pkl",

    compress=3

)

print("="*60)
print("Agent 3 Pipeline Saved Successfully")
print("File : agent3_complete_pipeline.pkl")
print("="*60)
