# -*- coding: utf-8 -*-
"""compute_agent2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhBLij4jl4mDT0WuD6i4KaktMugcS6i3
"""

!pip install pandas

!pip install numpy

!pip install openpyxl

import pandas as pd
import numpy as np
import json

from google.colab import files

uploaded=files.upload()

df=pd.read_csv(

        "clean_dataset.csv"

)
with open(

"agent1_response.json"

) as file:

      agent1=json.load(file)

print(agent1)

WHO={

"Iron_Fe_mgL":0.3,

"Arsenic_As_mgL":0.01,

"Lead_Pb_mgL":0.01,

"Cadmium_Cd_mgL":0.003,

"Chromium_Cr_mgL":0.05,

"Mercury_Hg_mgL":0.001,

"Nickel_Ni_mgL":0.07,

"Copper_Cu_mgL":2,

"Zinc_Zn_mgL":3,

"Manganese_Mn_mgL":0.4,

"Selenium_Se_mgL":0.04

}
IDEAL_VALUES={

metal:0

for metal in WHO

}

def calculate_hmpi(row):


      numerator=0

      denominator=0


      for metal in WHO:


            Mi=row[metal]

            Si=WHO[metal]

            Ii=IDEAL_VALUES[metal]


            Wi=1/Si


            Qi=((Mi-Ii)/(Si-Ii))*100


            numerator+=(Wi*Qi)

            denominator+=Wi


      return numerator/denominator

def calculate_hei(row):


      hei=0


      for metal in WHO:


            Hc=row[metal]

            Hmac=WHO[metal]


            hei+=(Hc/Hmac)


      return hei

def calculate_cd(row):


      cd=0


      for metal in WHO:


            CA=row[metal]

            CN=WHO[metal]


            cd+=((CA/CN)-1)


      return cd

def calculate_mi(row):


      mi=0


      for metal in WHO:


            Ci=row[metal]

            MAC=WHO[metal]


            mi+=(Ci/MAC)


      return mi

def composite_index(


        hmpi,

        hei,

        cd,

        mi

):


      score=(


      0.40*hmpi+

      0.25*hei+

      0.20*cd+

      0.15*mi


      )


      return score

def severity(ci):


      if ci<100:

            return "SAFE"


      elif ci<300:

            return "MODERATE"


      else:

            return "CRITICAL"

HMPI=[]

HEI=[]

CD=[]

MI=[]

CI=[]

SEVERITY=[]

for index,row in df.iterrows():


      hmpi=calculate_hmpi(row)

      hei=calculate_hei(row)

      cd=calculate_cd(row)

      mi=calculate_mi(row)


      ci=composite_index(

            hmpi,

            hei,

            cd,

            mi

      )


      HMPI.append(hmpi)

      HEI.append(hei)

      CD.append(cd)

      MI.append(mi)

      CI.append(ci)

      SEVERITY.append(

            severity(ci)

      )

df["HMPI"]=HMPI

df["HEI"]=HEI

df["Cd"]=CD

df["MI"]=MI

df["Composite_Index"]=CI

df["Severity"]=SEVERITY

df.to_csv(

"sample_wise_indices.csv",

index=False

)

average_hmpi=np.mean(HMPI)

maximum_hmpi=np.max(HMPI)

minimum_hmpi=np.min(HMPI)

average_hei=np.mean(HEI)

average_cd=np.mean(CD)

average_mi=np.mean(MI)

average_ci=np.mean(CI)

critical_samples=(

df["Severity"]

=="CRITICAL"

).sum()

overall_severity=severity(

        average_ci

)

response={


"rows_processed":

len(df),


"average_HMPI":

round(

average_hmpi,2

),


"maximum_HMPI":

round(

maximum_hmpi,2

),


"minimum_HMPI":

round(

minimum_hmpi,2

),


"average_HEI":

round(

average_hei,2

),


"average_Cd":

round(

average_cd,2

),


"average_MI":

round(

average_mi,2

),


"average_Composite_Index":

round(

average_ci,2

),


"pollution_severity":

overall_severity,


"critical_samples":

int(

critical_samples

),


"confidence_score":

agent1[

"confidence_score"

],


"ready_for_agent3":

True

}

with open(

"agent2_response.json",

"w"

) as file:


      json.dump(

      response,

      file,

      indent=4

      )

files.download(

"sample_wise_indices.csv"

)

files.download(

"agent2_response.json"

)

