# -*- coding: utf-8 -*-
"""preprocessing_agent1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksTq1CnvHuB42AZPj1i5x0B653Xz7a9i
"""

!pip install pandas numpy scikit-learn openpyxl joblib

import pandas as pd
import numpy as np
import json
import joblib

from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

from google.colab import files

uploaded = files.upload()

df = pd.read_excel("groundwater_rawdata.xlsx")

print(df.shape)

df.head()

df.info()

df.describe()

print(df.isnull().sum())

metal_columns = [

    "Iron_Fe_mgL",
    "Arsenic_As_mgL",
    "Lead_Pb_mgL",
    "Cadmium_Cd_mgL",
    "Chromium_Cr_mgL",
    "Mercury_Hg_mgL",
    "Nickel_Ni_mgL",
    "Copper_Cu_mgL",
    "Zinc_Zn_mgL",
    "Manganese_Mn_mgL",
    "Selenium_Se_mgL"

]

WHO_LIMITS = {

    "Iron_Fe_mgL":0.3,
    "Arsenic_As_mgL":0.01,
    "Lead_Pb_mgL":0.01,
    "Cadmium_Cd_mgL":0.003,
    "Chromium_Cr_mgL":0.05,
    "Mercury_Hg_mgL":0.001,
    "Nickel_Ni_mgL":0.07,
    "Copper_Cu_mgL":2,
    "Zinc_Zn_mgL":3,
    "Manganese_Mn_mgL":0.4,
    "Selenium_Se_mgL":0.04

}

missing_values = int(df.isnull().sum().sum())

duplicates = int(df.duplicated().sum())

print("Missing:",missing_values)
print("Duplicates:",duplicates)

numeric_cols = df.select_dtypes(include=np.number).columns

imputer = KNNImputer(n_neighbors=5)

df[numeric_cols] = imputer.fit_transform(
    df[numeric_cols]
)

joblib.dump(
    imputer,
    "agent1_imputer.pkl"
)

iso = IsolationForest(
    contamination=0.02,
    random_state=42
)

outlier_labels = iso.fit_predict(
    df[numeric_cols]
)

df["Outlier"] = outlier_labels

outlier_count = int(
    (df["Outlier"]==-1).sum()
)

print(outlier_count)

clean_df = df[
    df["Outlier"]==1
].copy()

clean_df.drop(
    columns=["Outlier"],
    inplace=True
)

scaler = StandardScaler()

scaled_features = scaler.fit_transform(
    clean_df[numeric_cols]
)

joblib.dump(
    scaler,
    "agent1_scaler.pkl"
)

critical_metals = []

moderate_metals = []

safe_metals = []

for metal in metal_columns:

    avg_val = clean_df[metal].mean()

    limit = WHO_LIMITS[metal]

    ratio = avg_val / limit

    if ratio >= 5:

        critical_metals.append(metal)

    elif ratio >= 1:

        moderate_metals.append(metal)

    else:

        safe_metals.append(metal)

contamination_scores = {}

for metal in metal_columns:

    contamination_scores[metal] = (

        clean_df[metal].mean()

        /

        WHO_LIMITS[metal]

    )

dominant_metals = sorted(

    contamination_scores,

    key=contamination_scores.get,

    reverse=True

)[:5]

critical_samples = 0
for metal in metal_columns:

    critical_samples += int(

        (
            clean_df[metal]

            >

            WHO_LIMITS[metal]

        ).sum()

    )

state_risk = {}
for state in clean_df["State"].unique():

    temp = clean_df[
        clean_df["State"]==state
    ]

    exceed_count = 0

    for metal in metal_columns:

        exceed_count += (

            temp[metal]

            >

            WHO_LIMITS[metal]

        ).sum()

    state_risk[state] = exceed_count
    top_states = sorted(

    state_risk,

    key=state_risk.get,

    reverse=True

)[:5]

confidence = 100
confidence -= missing_values * 0.05

confidence -= duplicates * 0.05

confidence -= outlier_count * 0.02

confidence = max(
    confidence,
    0
)

confidence = round(
    confidence,
    2
)

if confidence >= 90:

    quality = "Excellent"

elif confidence >= 75:

    quality = "Good"

elif confidence >= 50:

    quality = "Average"

else:

    quality = "Poor"

agent1_response = {

    "rows_processed": int(len(clean_df)),

    "confidence_score": confidence,

    "dataset_quality": quality,

    "critical_metals": critical_metals,

    "moderate_metals": moderate_metals,

    "safe_metals": safe_metals,

    "dominant_contaminants": dominant_metals,

    "critical_samples": int(critical_samples),

    "top_contaminated_states": top_states,

    "outliers_detected": int(outlier_count),

    "ready_for_agent2": True

}

print(
    json.dumps(
        agent1_response,
        indent=4
    )
)

with open(
    "agent1_response.json",
    "w"
) as f:

    json.dump(
        agent1_response,
        f,
        indent=4
    )

clean_df.to_csv(

    "clean_dataset.csv",

    index=False

)

files.download(
    "clean_dataset.csv"
)

files.download(
    "agent1_response.json"
)

