export const reportsData = [
  {
    region: "AuchandiPz",
    date: "2024-03-05",
    metal: "Lead",
    hpi: 75,
    status: "Alert",
    lat: 28.7041,
    lng: 77.1025,
    cause: "High vehicular and industrial emissions in nearby industrial zone.",
    ci: 0.72,
    ml: "Moderate risk; predicts increasing trend due to atmospheric deposition.",
  },
  {
    region: "Bakoli",
    date: "2024-03-14",
    metal: "Mercury",
    hpi: 4,
    status: "Safe",
    lat: 28.65,
    lng: 77.08,
    cause: "Proximity to agricultural fields with minimal chemical runoff.",
    ci: 0.38,
    ml: "Low risk; stable category, no significant anomalies detected.",
  },
  {
    region: "Balbir Nagar",
    date: "2024-04-09",
    metal: "Cadmium",
    hpi: 102,
    status: "Critical",
    lat: 28.6838,
    lng: 77.2908,
    cause: "Industrial effluents from nearby metal plating units.",
    ci: 0.95,
    ml: "High risk; persistent exceedance pattern linked to industrial discharge.",
  },
  {
    region: "Bankner",
    date: "2024-05-21",
    metal: "Arsenic",
    hpi: 82,
    status: "Alert",
    lat: 28.62,
    lng: 77.32,
    cause:
      "Construction activities and disturbed subsurface layers affecting arsenic mobilization.",
    ci: 0.78,
    ml: "Moderate-high risk; sporadic spikes under low groundwater recharge.",
  },
  {
    region: "Bapraula",
    date: "2024-06-16",
    metal: "Nickel",
    hpi: 63,
    status: "Alert",
    lat: 28.78,
    lng: 77.15,
    cause: "Mixed residential zone with limited anthropogenic pressure.",
    ci: 0.52,
    ml: "Low risk; prediction stable within safe range for next quarter.",
  },
  {
    region: "Barwala",
    date: "2024-03-27",
    metal: "Lead",
    hpi: 89,
    status: "Alert",
    lat: 28.72,
    lng: 77.05,
    cause: "Battery recycling and informal e-waste processing vicinity.",
    ci: 0.84,
    ml: "High-moderate risk; upward trend influenced by dry season runoff.",
  },
  {
    region: "Bawana IE Store",
    date: "2024-04-16",
    metal: "Mercury",
    hpi: 58,
    status: "Alert",
    lat: 28.795,
    lng: 77.045,
    cause: "Industrial estate nearby but regular monitoring reduces risk.",
    ci: 0.53,
    ml: "Low-moderate risk; improvement after intervention measures.",
  },
  {
    region: "Bhalaswa Lake",
    date: "2024-05-04",
    metal: "Cadmium",
    hpi: 95,
    status: "Alert",
    lat: 28.74,
    lng: 77.17,
    cause:
      "Contaminated leachate flow from landfill adjoining freshwater lake.",
    ci: 0.91,
    ml: "High risk; recurring heavy metal load from precipitation events.",
  },
  {
    region: "Bhatti",
    date: "2024-06-01",
    metal: "Arsenic",
    hpi: 86,
    status: "Alert",
    lat: 28.48,
    lng: 77.3,
    cause: "Rock-weathering enriched with natural arsenic mobilization.",
    ci: 0.81,
    ml: "Moderate-high risk; forecasts seasonal variations based on groundwater dynamics.",
  },
  {
    region: "Burari",
    date: "2024-07-10",
    metal: "Nickel",
    hpi: 51,
    status: "Alert",
    lat: 28.7539,
    lng: 77.1948,
    cause:
      "Proximity to residential zones with regular water treatment measures.",
    ci: 0.47,
    ml: "Moderate risk; consistent as 'Alert' across previous samples.",
  },
  {
    region: "Burari DJB Ex. Engg. Office",
    date: "2024-03-30",
    metal: "Lead",
    hpi: 77,
    status: "Alert",
    lat: 28.76,
    lng: 77.2,
    cause: "Old plumbing systems and traffic pollution.",
    ci: 0.71,
    ml: "Moderate risk; predicts peak risk during summer due to lower water volume.",
  },
  {
    region: "CBD Shahdara",
    date: "2024-04-22",
    metal: "Mercury",
    hpi: 45,
    status: "Safe",
    lat: 28.67,
    lng: 77.29,
    cause: "Managed green buffer and low industrial activity.",
    ci: 0.41,
    ml: "Low risk; stable prediction for safe status.",
  },
  {
    region: "Chandni Chowk",
    date: "2024-05-14",
    metal: "Cadmium",
    hpi: 99,
    status: "Alert",
    lat: 28.656,
    lng: 77.2322,
    cause:
      "Old infrastructure and localized industrial runoff in commercial core.",
    ci: 0.93,
    ml: "High risk; persistent contamination linked to drainage density.",
  },
  {
    region: "Chilla Regulator",
    date: "2024-06-18",
    metal: "Arsenic",
    hpi: 93,
    status: "Alert",
    lat: 28.63,
    lng: 77.31,
    cause:
      "Flow regulation impacts natural dilution and leads to concentration of pollutants.",
    ci: 0.81,
    ml: "Moderate-high risk; anomalies during low flow season.",
  },
  {
    region: "Daulatpur",
    date: "2024-07-04",
    metal: "Nickel",
    hpi: 6,
    status: "Safe",
    lat: 28.61,
    lng: 77.34,
    cause: "Dominantly open fields, minimal pollutant sources nearby.",
    ci: 0.55,
    ml: "Low risk; predicts stable water quality.",
  },
  {
    region: "Dwarka Sec 23 DDA Park",
    date: "2024-03-18",
    metal: "Lead",
    hpi: 81,
    status: "Alert",
    lat: 28.592,
    lng: 77.0463,
    cause: "Urban park near major roads with ongoing construction.",
    ci: 0.74,
    ml: "Moderate risk; construction activity drives periodic spikes.",
  },
  {
    region: "Dwarka Sec 5 DDA Park",
    date: "2024-04-14",
    metal: "Mercury",
    hpi: 49,
    status: "Safe",
    lat: 28.595,
    lng: 77.05,
    cause: "Well-maintained urban park with fresh water inflow.",
    ci: 0.45,
    ml: "Low risk; forecast within safe limits this season.",
  },
  {
    region: "Gadaipur",
    date: "2024-05-29",
    metal: "Cadmium",
    hpi: 105,
    status: "Critical",
    lat: 28.42,
    lng: 77.15,
    cause: "Nearby small industries, untreated effluent discharges.",
    ci: 0.98,
    ml: "High risk; anomaly consistently linked to local effluent events.",
  },
  {
    region: "Gazipur Crossing",
    date: "2024-06-22",
    metal: "Arsenic",
    hpi: 88,
    status: "Alert",
    lat: 28.605,
    lng: 77.42,
    cause: "Landfill leachate and construction runoff from expressway.",
    ci: 0.82,
    ml: "Moderate-high risk; risk peaking after heavy rainfall.",
  },
  {
    region: "GK 2",
    date: "2024-07-27",
    metal: "Nickel",
    hpi: 67,
    status: "Alert",
    lat: 28.5336,
    lng: 77.2425,
    cause: "Primarily residential area, effective sewage management.",
    ci: 0.61,
    ml: "Low-moderate risk; low but rising nickel content during summer.",
  },
  {
    region: "Haiderpur",
    date: "2024-03-08",
    metal: "Lead",
    hpi: 76,
    status: "Alert",
    lat: 28.71,
    lng: 77.12,
    cause: "Major water treatment works upstream releases trace metals.",
    ci: 0.71,
    ml: "Moderate risk; forecast improves with planned upgrades in treatment.",
  },
  {
    region: "Hareoli",
    date: "2024-04-18",
    metal: "Mercury",
    hpi: 46,
    status: "Safe",
    lat: 28.765,
    lng: 77.08,
    cause: "Agricultural runoff, but controlled pesticide use keeps risk low.",
    ci: 0.39,
    ml: "Low risk; minor fluctuations only.",
  },
  {
    region: "Hirankudna",
    date: "2024-07-21",
    metal: "Nickel",
    hpi: 97,
    status: "Alert",
    lat: 28.58,
    lng: 77.02,
    cause:
      "Electroplating and machinery manufacturing hub causing surface discharge.",
    ci: 0.96,
    ml: "High risk; anomaly cluster matching industrial discharge trend.",
  },
  {
    region: "Hiranki Village",
    date: "2024-06-07",
    metal: "Arsenic",
    hpi: 83,
    status: "Alert",
    lat: 28.575,
    lng: 77.015,
    cause: "Contaminated shallow aquifer due to intensive groundwater usage.",
    ci: 0.79,
    ml: "Moderate risk; periodic escalation after dry spells.",
  },
  {
    region: "India Gate Pz",
    date: "2024-07-16",
    metal: "Cadmium",
    hpi: 59,
    status: "Alert",
    lat: 28.6129,
    lng: 77.2295,
    cause: "Landscaped park area with ample fresh water supply.",
    ci: 0.49,
    ml: "Moderate risk; status 'Alert' with transient small fluctuations.",
  },
  {
    region: "JNU",
    date: "2024-03-24",
    metal: "Lead",
    hpi: 78,
    status: "Alert",
    lat: 28.54,
    lng: 77.17,
    cause: "Old academic buildings and limited nearby traffic emissions.",
    ci: 0.72,
    ml: "Moderate risk; stable with minor increases after rainfall events.",
  },
  {
    region: "Jagatpur",
    date: "2024-04-12",
    metal: "Mercury",
    hpi: 51,
    status: "Alert",
    lat: 28.7,
    lng: 77.35,
    cause: "Managed green area, low mercury sources identified.",
    ci: 0.44,
    ml: "Low-moderate risk; continued safety.",
  },
  {
    region: "Jaitpur Khadar",
    date: "2024-05-20",
    metal: "Cadmium",
    hpi: 103,
    status: "Critical",
    lat: 28.56,
    lng: 77.32,
    cause:
      "Surface water inflow contaminated by upstream industrial discharges.",
    ci: 0.97,
    ml: "High risk; trend isolated to wet season pollution.",
  },
  {
    region: "Jamali Kamali",
    date: "2024-06-14",
    metal: "Arsenic",
    hpi: 91,
    status: "Alert",
    lat: 28.52,
    lng: 77.185,
    cause:
      "Subsurface arsenic enrichment due to soil chemistry and shallow groundwater retention.",
    ci: 0.85,
    ml: "Moderate-high risk; potential shift to critical if recharge decreases.",
  },
  {
    region: "Janakpuri",
    date: "2024-07-09",
    metal: "Nickel",
    hpi: 54,
    status: "Alert",
    lat: 28.6248,
    lng: 77.0904,
    cause: "Urban residential area with efficient water management.",
    ci: 0.5,
    ml: "Moderate risk; category holds steady.",
  },
  {
    region: "Jaunapur",
    date: "2024-03-28",
    metal: "Nickel",
    hpi: 8,
    status: "Safe",
    lat: 28.45,
    lng: 77.28,
    cause: "Growing industrial activity, new units established recently.",
    ci: 0.77,
    ml: "Moderate risk; predicts rising trend with further industrialization.",
  },
  {
    region: "Jaunti",
    date: "2024-04-21",
    metal: "Mercury",
    hpi: 47,
    status: "Safe",
    lat: 28.44,
    lng: 77.27,
    cause: "Primarily open area, few potential sources.",
    ci: 0.42,
    ml: "Low risk; trend stable.",
  },
  {
    region: "Jheel Khoh",
    date: "2024-05-13",
    metal: "Cadmium",
    hpi: 108,
    status: "Critical",
    lat: 28.68,
    lng: 77.37,
    cause: "Seasonal influx from upstream industrial areas.",
    ci: 0.99,
    ml: "High risk; forecasts anomalous peaks during summer.",
  },
  {
    region: "Jhuljhuli",
    date: "2024-06-19",
    metal: "Arsenic",
    hpi: 9,
    status: "Safe",
    lat: 28.69,
    lng: 77.38,
    cause: "Construction and land use change boosting enrichment.",
    ci: 0.84,
    ml: "Moderate-high risk; alert risk if activities persist.",
  },
  {
    region: "Kanjhawala",
    date: "2024-07-14",
    metal: "Lead",
    hpi: 32,
    status: "Safe",
    lat: 28.73,
    lng: 76.95,
    cause: "Low-density habitation, no major sources nearby.",
    ci: 0.59,
    ml: "Low risk; predicts sustained safe levels.",
  },
  {
    region: "Khela Ghat Bhela Road",
    date: "2024-03-12",
    metal: "Lead",
    hpi: 84,
    status: "Alert",
    lat: 28.64,
    lng: 77.36,
    cause: "Riverside with some unregulated dumping.",
    ci: 0.77,
    ml: "Moderate risk; expects risk reduction with improved regulation.",
  },
  {
    region: "Khera Kalan",
    date: "2024-04-17",
    metal: "Mercury",
    hpi: 44,
    status: "Safe",
    lat: 28.75,
    lng: 77.02,
    cause: "Semi-rural, minimal mercury sources.",
    ci: 0.4,
    ml: "Low risk; continued safety.",
  },
  {
    region: "Kingsway Camp Police Ground",
    date: "2024-05-10",
    metal: "Cadmium",
    hpi: 101,
    status: "Critical",
    lat: 28.71,
    lng: 77.21,
    cause: "Old pipes, commercial activities in adjacent zones.",
    ci: 0.96,
    ml: "High risk; predicts high risk till infrastructure replacement.",
  },
  {
    region: "Lodhi Garden",
    date: "2024-06-23",
    metal: "Arsenic",
    hpi: 85,
    status: "Alert",
    lat: 28.5937,
    lng: 77.2218,
    cause:
      "Intensive gardening and use of fertilizers enhancing trace metal accumulation.",
    ci: 0.79,
    ml: "Moderate-high risk; forecasts slight increase under higher evapotranspiration.",
  },
  {
    region: "MahabirVansth.",
    date: "2024-05-11",
    metal: "Mercury",
    hpi: 106,
    status: "Critical",
    lat: 28.6,
    lng: 77.27,
    cause: "Forest area with little to no contamination sources.",
    ci: 0.57,
    ml: "High risk; 'Critical' and fluctuate.",
  },
  {
    region: "MajaraDabas",
    date: "2024-03-09",
    metal: "Nickel",
    hpi: 74,
    status: "Alert",
    lat: 28.63,
    lng: 76.98,
    cause: "High enrichment factor from local waste processing.",
    ci: 0.73,
    ml: "Moderate risk; trend rising with waste activity.",
  },
  {
    region: "Majnu ka Tila",
    date: "2024-04-15",
    metal: "Nickel",
    hpi: 42,
    status: "Safe",
    lat: 28.695,
    lng: 77.21,
    cause: "Riverbank location but managed waste disposal.",
    ci: 0.39,
    ml: "Low risk; category stays safe.",
  },
  {
    region: "Mangolpur",
    date: "2024-05-17",
    metal: "Cadmium",
    hpi: 106,
    status: "Critical",
    lat: 28.76,
    lng: 77.11,
    cause: "Electronic and automobile workshops nearby.",
    ci: 0.98,
    ml: "High risk; detects cluster anomaly in metal concentrations.",
  },
  {
    region: "Mayur Vihar",
    date: "2024-07-30",
    metal: "Arsenic",
    hpi: 87,
    status: "Alert",
    lat: 28.61,
    lng: 77.29,
    cause:
      "Urban construction activity and groundwater overextraction influencing arsenic solubility.",
    ci: 0.83,
    ml: "Moderate-high risk; stable-to-worsening phase for next cycle.",
  },
  {
    region: "Najafgarh",
    date: "2024-06-09",
    metal: "Lead",
    hpi: 41,
    status: "Safe",
    lat: 28.609,
    lng: 76.9855,
    cause:
      "Water sourced from mixed domestic and commercial supply with minimal contamination.",
    ci: 0.55,
    ml: "Low risk; ranked as 'Safe', no anomaly detected in 6-month rolling forecast.",
  },
];

export const COLORS = {
  primary: "#007BFF",
  primaryLight: "#339CFF",
  primaryDark: "#0056B3",
};

export const languages = [
  "English",
  "हिन्दी",
  "മലയാളം",
  "తెలుగు",
  "ಕನ್ನಡ",
  "اردو",
  "ଓଡିଆ",
];

export const notifications = [
  "Email Alerts",
  "SMS Notifications",
  "Push Notifications",
  "In-App Messages",
  "Weekly Summaries",
];
